config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  get 'signup' => 'users#new', as: :new_user
  post 'signup' => 'users#create', as: :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'splash' => 'users#splash'

  get 'search' => 'dogs#index'
  post 'results' => 'dogs#show'
  get 'results' => 'dogs#show'

  post 'favorites' => 'favorites#create'

  get 'favorites' => 'favorites#show', as: 'user_favorites'

  delete 'favorites/:id' => 'favorites#destroy', as: 'destroy_favorite'

  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :users

end

app/models/dogs_users.rb
class DogsUsers < ActiveRecord::Base
  belongs_to :dog
  belongs_to :user

  validates_uniqueness_of :dog_id, scope: :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :dogs

  has_and_belongs_to_many :dogs

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: {with: /@/}

  def display_name
    self.name || 'Dog Lover'
  end

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def check_auth
    unless current_user
      flash[:warning] = "You have to be logged in."
      redirect_to login_path
    end
  end

  def check_no_auth
    # redirect_to root_path if current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    before_action :check_auth
    protect_from_forgery :except => :show
require 'petfinder'

  def index

  end

  def create

  end


  def show
    @petfinder = Petfinder::Client.new(ENV['PETFINDER_API'], ENV['PETFINDER_SECRET'])
    animal = 'dog'
    @zip_code = params[:search]
    @dogs = @petfinder.find_pets(animal, @zip_code)

    @dogs_db = []

    @dogs.each do |dog|
      @dogs_pic = dog.photos[0].medium if dog.photos[0]

      search_dog = Dog.find_by pf_id: dog.id
        if search_dog != nil
          @saveDog = search_dog
        else
          @saveDog = Dog.new({"name" => dog.name, "pf_id" => dog.id, "description" => dog.description,
        "photo" => @dogs_pic})
          @saveDog.save
        end
      @dogs_db << @saveDog
    end


  end




end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :check_auth
   protect_from_forgery :except => :show



  def create
    @favorite = DogsUsers.new({"dog_id" => params[:dog_id], "user_id" => session[:user_id]})
    @favorite.save

  end

  def show
    @favorites = DogsUsers.where user_id: session[:user_id]
  end


  def destroy
    DogsUsers.find(params[:id]).delete
    redirect_to user_favorites_path

  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :check_no_auth, except: [:destroy]


  def new
  end

  def create
    user = User.authenticate(params[:user][:email], params[:user][:password])
    if(user)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:danger] = "Invalid email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "You are logged out."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_no_auth

  def index
    unless current_user
      redirect_to splash_path
    end
  end

  def splash

  end


  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      flash[:success] = "Thanks for signing up! Login below."
      redirect_to login_path
    else
      flash[:danger] = @user.errors.full_messages.uniq.to_sentence
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,:name,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/index.html.erb
<div class='welcome'>
<h1>Find a pup near you!</h1>

  <div class="form-group">
<%= bootstrap_form_tag url: results_path do |f| %>
  <%= f.search_field :search, placeholder: "Zip Code" %>
  <%= f.primary "Find my best friend!" %>
<% end %>

</div>
<br>
</div>

app/views/dogs/show.html.erb
<%= csrf_meta_tag %>

<center>
<div class="container"><br>
<div class = "row">
<div class = "wrap">
  <div id="tinderslide">
    <ul>
         <% @dogs_db.each do |dog| %>
        <li class="pane1"><div class="img">
          <%= image_tag dog.photo%>
        </div><div>
        <span class="dog_id"><%= dog.id %></span>,
        <%= dog.name %>,
        </div><div class="like"></div><div class="dislike"></div></li>
         <% end %>
    </ul>

  </div>
   <div class = "actions">
    <a href="#" class = "dislike"><i></i></a>
    <a href="#" class = "like"><i></i></a>
  </div>

</div>

</div>
</div>

</center>

<!-- <div>
<% #@pets.each do |dog| %>
<div class="well">
  <%#= image_tag dog.photos[0].large if dog.photos[0]%><br>
  Name: <%#= dog.name %><br>

  Age: <%#= dog.age%><br>

  Breed: <%#= breeds = dog.breeds
    breeds.map(&:inspect).join(', ')%><br>

  Shelter Info: <ul>
  <li><%#= @petfinder.shelter(dog.shelter_id).name %></li>
  <li><%#= @petfinder.shelter(dog.shelter_id).email%></li>
  <li><%#= city = dog.city
  city.map(&:inspect).join(', ').chomp %></li>
  </ul>
  Size: <%#= dog.size %><br>

  Sex: <%#= dog.sex%><br>

  Description: <%#= dog.description%><br>

</div>
<% #end %>
</div> -->

app/views/favorites/show.html.erb
<center>
<div class="container">
<div class="row">

<div class="col-md-5 col-md-offset-4">
 <% @favorites.each do |favorite| %>
 <div class="well">
       <div class="img">
          <%= image_tag favorite.dog.photo%>
        </div><br>
        <a href="#<%=favorite.dog.id %>" class="toggle btn btn-primary"> <%= favorite.dog.name %>'s Info </a>
        <%= link_to "", destroy_favorite_path(favorite), method: :delete, class: 'btn btn-danger btn-sm glyphicon glyphicon-remove', data: {confirm: "Are you sure?"} %><br>
        <br> <div id="<%=favorite.dog.id %>" class="well hidden">
        <span class="dog_id">WOOFr ID: <%= favorite.dog.id %></span><br>
        <h3><%= favorite.dog.name %></h3><br>
        <%= favorite.dog.description %>

    </div>
    </div>
     <% end %>
</div>
</div>
</div>
</center>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">

  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">WOOFr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Search", "/search" %></a></li>
        <li><%= link_to "Buddies", "/favorites" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.display_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li><a href="#">Settings</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out",logout_path %></a></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/signup">Sign Up</a></li>
          <li><a href="/login">Log In</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WOOFr</title>
   <%= favicon_link_tag 'favicon.png' %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="style.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/nav' %>
<div class="container">
  <div class="row">
    <%= render partial: 'shared/flash' %>

    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="wrapper">
<div class='welcome'>
<h1> Welcome to WOOFr! </h1>
<p>WOOFr is a fun way to find a best friend for anyone.
There are a lot of sweet dogs out there that need a
 home and someone to adore.</p>

 <h3>WOOFr is easy to use!</h3>
 <p>1.) Enter in your zip code.<b>
 2.) Swipe right for potential besties.<br>
 3.) OR swipe left ifthey're just not the one.<br>
  (Or you can click on the buttons.)<br>
 4.) Go to your Buddies page to get more info<br>
 on your potential new friends.<br></p>
 <h3>Happy searching!</h3>
 <a class="btn btn-success" href="/search" role="button">Search!</a>
 <h4>I hope you find your new best friend :)</h4>
</div>
</div>

app/views/users/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Sign Up</h3>
    </div>
    <div class="panel-body">
      <%= bootstrap_form_for @user do |f| %>
        <%= f.text_field :email %>
        <%= f.text_field :name %>
        <%= f.password_field :password %>
        <%= f.primary "Join Now" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/splash.html.erb
<div class='wrapper'>
<div class='welcome'>
  <h1> Welcome to WOOFr! </h1>
<p>WOOFr is a Tinder style app to find you a furry friend!<br>
There are a lot of sweet dogs out there that need a
 home and someone to adore.<br> You can be that someone!
 Start your search to adopt a dog here!</p>

 <h3>All you have to do is sign up!</h3>
 <p>Happy searching!</p>
 <a class="btn btn-success" href="/signup" role="button">Sign Up!</a>
 <h4>I hope you find your new best friend :)</h4>
</div>
</div>